{{ if and .Values.arenaService.enabled .Values.arenaService.rwMode }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: arena-service-write
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: arena-service-write
  namespace: {{ $.Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arena-service-write
  serviceName: arena-service-write
  template:
    metadata:
      labels:
        app: arena-service-write
    spec:
      containers:
        - args:
            - ArenaService.dll
          command:
            - dotnet
          env:
            - name: Rpc__Host
              valueFrom:
                secretKeyRef:
                  key: rpc-host
                  name: arena
            - name: Redis__ConnectionString
              valueFrom:
                secretKeyRef:
                  key: redis-connection-string
                  name: arena
            - name: Redis__TimeOut
              value: "5000"
            - name: Redis__Database
              valueFrom:
                secretKeyRef:
                  key: redis-database
                  name: arena
          {{- with $.Values.arenaService.envForWrite }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ $.Values.arenaService.image.repository }}:{{ $.Values.arenaService.image.tag }}
          name: arena-service-write
          ports:
            - containerPort: 80
      restartPolicy: Always
      {{- with $.Values.arenaService.nodeSelector.write }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  updateStrategy:
    type: RollingUpdate
{{ end }}
