name: Test internal chain

on:
  workflow_dispatch:
    inputs:
      network:
        required: true
        description: 'internal network name'
        default: 'odin-internal'
        type: choice
        options:
        - odin-internal
        - heimdall-internal
      offset:
        required: true
        description: 'Insert the snapshot tip index of the internal network (e.g. 1115268)'
      limit:
        required: true
        description: 'Insert how many blocks from the mainnet to test (e.g. 100)'
      delay_interval:
        required: false
        default: 0
        description: 'Insert the delay interval(sec) when staging the mainnet txs to the internal network per block (default: 0)'

jobs:
  test-internal-chain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.10.13

    - run: |
        python -m pip install -r requirements.txt
        flit install
      name: install dependencies
      working-directory: ./scripts

    - name: Test internal chain
      run: |
        python cli.py test-internal-chain ${{ github.event.inputs.network }} ${{ github.event.inputs.offset }} ${{ github.event.inputs.limit }} ${{ github.event.inputs.delay_interval }}
      working-directory: ./scripts
      env:
        GITHUB_TOKEN: ${{ secrets.P_GITHUB_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
